language: go
dist: xenial
sudo: required
services:
  - docker
script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - cd ${TRAVIS_BUILD_DIR}/dockerfiles/base
  - make docker_build
  - make docker_push
after_script:
  - curl -X POST https://hooks.microbadger.com/images/carml/base/Y5oB6PYl8maUalSeWfNjOOUELjw=
