jobs:
  - job: CPU
    timeoutInMinutes: 0
    steps:
      - bash: |
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          cd dockerfiles/base
          make docker_build_cpu
          while $(make docker_push_cpu); do :; done
  - job: GPU
    timeoutInMinutes: 0
    steps:
      - bash: |
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          cd dockerfiles/base
          make docker_build_gpu
          while $(make docker_push_gpu); do :; done
  - job: CPU_MLPerf
    timeoutInMinutes: 0
    steps:
      - bash: |
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          cd dockerfiles/base
          make docker_build_cpu_mlperf
          while $(make docker_push_cpu_mlperf); do :; done
  - job: GPU_MLPerf
    timeoutInMinutes: 0
    steps:
      - bash: |
          docker login -u $(DOCKER_USERNAME) -p $(DOCKER_PASSWORD)
          cd dockerfiles/base
          make docker_build_gpu_mlperf
          while $(make docker_push_gpu_mlperf); do :; done
  - job: Update_Microbadger
    dependsOn:
      - CPU
      - GPU
    steps:
      - script: "curl -X POST https://hooks.microbadger.com/images/carml/go-caffe2/AeELmVfl5ucS37qg1Me7vJwauZY="
